Watching for file changes with StatReloader
Session data corrupted
Not Found: /static/css/base.css
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Watching for file changes with StatReloader
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
Session data corrupted
Not Found: /static/css/base.css
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/account/urls.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/urls.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Session data corrupted
Session data corrupted
Session data corrupted
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 102, in image_list
    cached_response = cache.get(cache_key)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/cache/backends/redis.py", line 187, in get
    return self._cache.get(key, default)
           ^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/cache/backends/redis.py", line 172, in _cache
    return self._class(self._servers, **self._options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/cache/backends/redis.py", line 39, in __init__
    import redis
ModuleNotFoundError: No module named 'redis'
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/core/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 108, in image_list
    popular_images = Image.get_popular_images(limit=5)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/models.py", line 106, in get_popular_images
    return cls.objects.annotate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1673, in _annotate
    raise ValueError(
ValueError: The annotation 'total_likes' conflicts with a field on the model.
Watching for file changes with StatReloader
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 108, in image_list
    popular_images = Image.get_popular_images(limit=5)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/models.py", line 106, in get_popular_images
    return cls.objects.annotate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1673, in _annotate
    raise ValueError(
ValueError: The annotation 'total_likes' conflicts with a field on the model.
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 108, in image_list
    popular_images = Image.get_popular_images(limit=5)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/models.py", line 106, in get_popular_images
    return cls.objects.annotate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1673, in _annotate
    raise ValueError(
ValueError: The annotation 'total_likes' conflicts with a field on the model.
/mnt/data/Documents/Risav's personal codes/bookmark/images/models.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/images/models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 111, in image_list
    images = Image.objects.annotate(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1673, in _annotate
    raise ValueError(
ValueError: The annotation 'total_likes' conflicts with a field on the model.
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 111, in image_list
    images = Image.objects.annotate(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1673, in _annotate
    raise ValueError(
ValueError: The annotation 'total_likes' conflicts with a field on the model.
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 111, in image_list
    images = Image.objects.annotate(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1673, in _annotate
    raise ValueError(
ValueError: The annotation 'total_likes' conflicts with a field on the model.
/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 136, in image_list
    response = render(
               ^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: images/image/list.html
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 136, in image_list
    response = render(
               ^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: images/image/list.html
/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/images/urls.py changed, reloading.
Watching for file changes with StatReloader
/mnt/data/Documents/Risav's personal codes/bookmark/images/models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'thumbnail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 88, in image_list
    return render(
           ^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 1096, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 1036, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'thumbnail' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
debugger_tags
highlighting
i18n
indent_text
l10n
log
static
syntax_color
tz
widont
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /images/
Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/images/views.py", line 88, in image_list
    return render(
           ^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 190, in thumbnail
    return ThumbnailNode(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 116, in __init__
    self.nodelist_file = parser.parse(('empty', 'endthumbnail',))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/mnt/data/Documents/Risav's personal codes/bookmark/venv/lib/python3.12/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 16: 'endfor', expected 'empty' or 'endthumbnail'. Did you forget to register or load this tag?
